name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES

categories:
  - title: "ðŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "ðŸ§° Maintenance"
    labels:
      - "chore"
  - title: "ðŸ“š Documentation"
    labels:
      - "docs"

autolabeler:
  - label: "feature"
    branch:
      - '/^feature\/.+/'
  - label: "bug"
    branch:
      - '/^fix\/.+/'
      - '/^hotfix\/.+/'
  - label: "chore"
    branch:
      - '/^chore\/.+/'
  - label: "docs"
    branch:
      - '/^docs\/.+/'

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
