name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - main
    paths:
      - package.json

env:
  packageName: "com.elypha.vpm.material-helper"
  pagesRepo: "Elypha/unity-helper"

jobs:
  build-assets:
    runs-on: ubuntu-latest
    outputs:
      packageVersion: ${{ steps.info.outputs.packageVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Prepare package information
        id: info
        run: |
          packageVersion=$(jq -r '.version' package.json)
          echo "packageVersion=${packageVersion}" >> $GITHUB_OUTPUT
          echo "zipName=${{ env.packageName }}-${packageVersion}.zip" >> $GITHUB_OUTPUT
          echo "unitypackageName=${{ env.packageName }}-${packageVersion}.unitypackage" >> $GITHUB_OUTPUT

      # <ref: create unitypackage https://github.com/pCYSl5EDgo/create-unitypackage
      - name: Set metadata list
        run: find ./ -name \*.meta >> metaList
      - name: Create .unitypackage
        uses: pCYSl5EDgo/create-unitypackage@b5c57408698b1fab8b3a84d4b67f767b8b7c0be9
        with:
          package-path: ${{ steps.info.outputs.unitypackageName }}
          include-files: metaList
      # />

      - name: Create zip
        run: zip -r ${{ steps.info.outputs.zipName }} . -x ".git/*" ".github/*"

      - name: Make Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.info.outputs.zipName }}
            ${{ steps.info.outputs.unitypackageName }}
            package.json
