name: Draft Release

on:
  push:
    branches:
      - main
      - master
  # pull_request:
  #   types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

# permissions:
#   contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
      issues: write  # required for labelling PRs as of 2025-07
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          # disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
