name: Notify to rebuild Pages

on:
  release:
    types: [published]

env:
  pagesRepo: "Elypha/unity-helper"
  targetEvent: "pages-rebuild"

jobs:
  notify-page-build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Pages build notification
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_PAGES_REBUILD }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ env.pagesRepo }}/dispatches" \
            -d '{"event_type":"${{ env.targetEvent }}", "client_payload": {"release_version": "${{ github.ref_name }}"}}'
